const lastName = '山田';
const firstName = '太郎';
const fullName = lastName + ' ' + firstName;
const myAge = 10;
const friendAge = 13;
const totalAge = myAge + friendAge;
const numberOfDays = totalAge * 365;
const numberOfChildren = 3;
const numberOfCakes = 10;
const numberOfCakesByChildren = 10 / 3;
const numberOfRestOfCakes = 10 % 3;
console.log(lastName);
console.log(firstName);
console.log(fullName);
console.log(myAge);
console.log(friendAge);
console.log(totalAge);
console.log(numberOfDays);
console.log(numberOfChildren);
console.log(numberOfCakes);
console.log(numberOfCakesByChildren);
console.log(numberOfRestOfCakes);
